CREATE TABLE "GCG_6381_TA_HEAD" (
 "TERMINAL_NO" CHAR(3),
 "BI_RUN_ID" LONGVARCHAR,
 "REPT_ID" INTEGER,
 "REPT_TYPE" CHAR(1),
 "SHIFT_NO" CHAR(5),
 "PAY_WEEK" CHAR(2),
 "PAY_DATE" DATE,
 "RUN_DATE" DATE );
